---
 - name: python installation on all servers
   hosts: all
   become: yes
   tasks:
     - name: installation of python
       apt:
        name: python3
        state: present
        update_cache: yes
